
scopes:
    training:
        label: 培训项目
        type: group
        modelClass: Samubra\Train\Models\Training
        conditions: training_id in (:filtered)
        nameFrom: title
    health:
        label: 健康状况
        type: group
        modelClass: Samubra\Train\Models\Lookup
        conditions: status_id in (:filtered)
        options: getHealthOptions
    status:
        label: 受理状态
        modelClass: Samubra\Train\Models\Lookup
        conditions: status_id in (:filtered)
        options: getStatusOptions
    pay:
        label: 已交费用
        type: number
        conditions: pay = ':filtered'
    created_at:
        label: 创建日期
        type: daterange
        yearRange: 2
        conditions: created_at >= ':after' AND created_at <= ':before'
    updated_at:
        label: 最后修改日期
        type: daterange
        yearRange: 2
        conditions: updated_at >= ':after' AND updated_at <= ':before'