plugin:
    name: 'samubra.train::lang.plugin.name'
    description: 'samubra.train::lang.plugin.description'
    author: samubra
    icon: oc-icon-cogs
    homepage: ''
permissions:
    train.manage.organ:
        tab: 发证机关管理
        label: 管理发证机关
    tran.mange.category:
        tab: 培训类别管理
        label: 管理培训类别
    train.manage.certificate:
        tab: 证书管理
        label: 管理培训证书
    train.manage.teacher:
        tab: 教师管理
        label: 管理授课教师
    train.manage.course:
        tab: 课程管理
        label: 管理课程
    train.manage.plan:
        tab: 方案管理
        label: 管理培训方案
    train.manage.project:
        tab: 培训项目管理
        label: 管理培训项目
navigation:
    meta:
        label: 数据管理
        url: samubra/train/categories
        icon: icon-suitcase
        permissions:
            - tran.mange.category
            - train.manage.organ
        sideMenu:
            meta-category:
                label: 培训类别管理
                url: samubra/train/categories
                icon: icon-stack-overflow
                permissions:
                    - tran.mange.category
            meta-organ:
                label: 发证机构管理
                url: samubra/train/organs
                icon: icon-sitemap
                permissions:
                    - train.manage.organ
            meta-teacher:
                label: 教师管理
                url: samubra/train/teachers
                icon: icon-user-md
                permissions:
                    - train.manage.teacher
            meta-course:
                label: 课程管理
                url: samubra/train/courses
                icon: icon-sitemap
                permissions:
                    - train.manage.course
    train:
        label: 培训管理
        url: samubra/train/certificates
        icon: icon-briefcase
        permissions:
            - train.manage.certificate
        sideMenu:
            train-project:
                label: 培训项目
                url: samubra/train/projects
                icon: icon-puzzle-piece
                permissions:
                    - train.manage.project
            train-plan:
                label: 培训方案
                url: samubra/train/plans
                icon: icon-paper-plane
                permissions:
                    - train.manage.plan
            train-certificate:
                label: 培训证书
                url: samubra/train/certificates
                icon: icon-certificate
                permissions:
                    - train.manage.certificate
