plugin:
    name: 'samubra.train::lang.plugin.name'
    description: 'samubra.train::lang.plugin.description'
    author: samubra
    icon: oc-icon-cogs
    homepage: ''
permissions:
    train.manage.organ:
        tab: 发证机关管理
        label: 管理发证机关
    tran.mange.category:
        tab: 培训类别管理
        label: 管理培训类别
    train.manage.certificate:
        tab: 证书管理
        label: 管理培训证书
    train.manage.teacher:
        tab: 教师管理
        label: 管理授课教师
navigation:
    train-meta:
        label: 数据管理
        url: samubra/train/categories
        icon: icon-suitcase
        permissions:
            - tran.mange.category
            - train.manage.organ
        sideMenu:
            train-meta-category:
                label: 培训类别管理
                url: samubra/train/categories
                icon: icon-stack-overflow
                permissions:
                    - tran.mange.category
            train-meta-organ:
                label: 发证机构管理
                url: samubra/train/organs
                icon: icon-sitemap
                permissions:
                    - train.manage.organ
            train-meta-teacher:
                label: 教师管理
                url: samubra/train/teachers
                icon: icon-user-md
                permissions:
                    - train.manage.teacher
    train.train:
        label: 培训管理
        url: samubra/train/certificates
        icon: icon-briefcase
        permissions:
            - train.manage.certificate
        sideMenu:
            train.train.certificate:
                label: 培训证书
                url: samubra/train/certificates
                icon: icon-certificate
                permissions:
                    - train.manage.certificate
