
scopes:
    member:
        label: 培训学员
        type: group
        modelClass: Samubra\Train\Models\Member
        conditions: member_id in (:filtered)
        nameFrom: member_name
    type:
        label: 培训类别
        type: group
        modelClass: Samubra\Train\Models\Category
        conditions: type_id in (:filtered)
        nameFrom: name
    edu:
        label: 文化程度
        type: group
        modelClass: Samubra\Train\Models\Lookup
        conditions: edu_id in (:filtered)
        options: getEduOptions
    first_get_date:
        label: 初领证日期
        type: daterange
        yearRange: 6
        conditions: first_get_date >= ':after' AND first_get_date <= ':before'
    print_date:
        label: 发证日期
        type: daterange
        yearRange: 6
        conditions: print_date >= ':after' AND print_date <= ':before'
    is_valid:
        label: 是否有效
        type: switch
        conditions:
            - is_valid <> true
            - is_valid = true
    created_at:
        label: 创建日期
        type: daterange
        yearRange: 2
        conditions: created_at >= ':after' AND created_at <= ':before'
    updated_at:
        label: 最后修改日期
        type: daterange
        yearRange: 2
        conditions: updated_at >= ':after' AND updated_at <= ':before'