name: 培训证书
modelClass: Samubra\Train\Models\Certificate
form: $/samubra/train/models/certificate/fields.yaml
defaultRedirect: samubra/train/certificates
create:
    title: 添加培训证书
    redirect: 'samubra/train/certificates/update/:id'
    redirectClose: samubra/train/certificates
    flashSave: 培训证书添加成功
update:
    title: 修改培训证书信息
    redirect: samubra/train/certificates
    redirectClose: samubra/train/certificate
    flashSave: 培训证书信息修改成功
    flashDelete: 培训证书删除成功
