# ===================================
#  Import/Export Behavior Config
# ===================================

import:
    title: 导入培训证书
    modelClass: Samubra\Train\Models\CertificatesImport
    list: $/samubra/train/models/certificate/import_columns.yaml

export:
    title: 导出培训证书
    modelClass: Samubra\Train\Models\CertificatesExport
    list: $/samubra/train/models/certificate/export_columns.yaml
    form: $/samubra/train/models/certificate/export_fields.yaml