title: 课程
modelClass: Samubra\Train\Models\Course
list: $/samubra/train/models/course/columns.yaml
recordUrl: 'samubra/train/courses/update/:id'
noRecordsMessage: 'backend::lang.list.no_records'
recordsPerPage: 20
showSetup: true
showCheckboxes: true
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
filter: config_filter.yaml