records:
    label: 证件类表
    recordsPerPage: 10
    view:
        list: $/samubra/train/models/record/columns.yaml
        toolbarButtons: create|delete
    manage:
        form: $/samubra/train/models/record/fields.yaml
        list: $/samubra/train/models/record/columns.yaml