
scopes:
    teacherEdu:
        label: 文化程度
        type: group
        modelClass: Samubra\Train\Models\Lookup
        conditions: teacher_edu_id in (:filtered)
        options: getEduOptions
    created_at:
        label: 创建日期
        type: daterange
        yearRange: 2
        conditions: created_at >= ':after' AND created_at <= ':before'
    updated_at:
        label: 最后修改日期
        type: daterange
        yearRange: 2
        conditions: updated_at >= ':after' AND updated_at <= ':before'