
scopes:
    type:
        label: 培训类别
        type: group
        modelClass: Samubra\Train\Models\Category
        conditions: type_id in (:filtered)
        nameFrom: name
    is_new:
        label: 是否新训
        type: switch
        conditions:
            - is_new <> true
            - is_new = true
    created_at:
        label: 创建日期
        type: daterange
        yearRange: 2
        conditions: created_at >= ':after' AND created_at <= ':before'
    updated_at:
        label: 最后修改日期
        type: daterange
        yearRange: 2
        conditions: updated_at >= ':after' AND updated_at <= ':before'