title: 培训项目
modelClass: Samubra\Train\Models\Project
list: $/samubra/train/models/project/columns.yaml
recordUrl: 'samubra/train/projects/update/:id'
noRecordsMessage: 'backend::lang.list.no_records'
recordsPerPage: 20
showSetup: true
showCheckboxes: true
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
