courses:
    label: 培训课程
    view:
        list: $/samubra/train/models/course/pivotColumns.yaml
        toolbarButtons: add|remove
    manage:
        list: $/samubra/train/models/course/columns.yaml
        recordsPerPage: 10
        showSearch: true
    pivot:
        form: $/samubra/train/models/course/pivotFields.yaml